version: '3.7'
services:
  zookeeper:
   image: "confluentinc/cp-zookeeper:7.1.2"
   hostname: zookeeper
   container_name: zookeeper
   ports:
     - "2181:2181"
   environment:
     TZ: Vietnam/Hanoi
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000

  kafka:
   image: "confluentinc/cp-kafka:7.1.2"
   hostname: kafka
   container_name: kafka
   depends_on:
     - zookeeper
   ports:
   # Exposes 9092 for external connections to the broker
   # Use kafka:29092 for connections internal on the docker network
     - "9092:9092"
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
     KAFKA_DELETE_TOPIC_ENABLE: "true"
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
     CONFLUENT_METRICS_ENABLE: 'false'

